// #Sireum
package bc.runtimemonitor

import org.sireum._
import bc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object ModelInfo {
  val TempSensor_i_tcp_tempSensor_MI : Component =
    Component(
      name = "TempSensor_i_tcp_tempSensor",
      id = Arch.BuildingControlDemo_i_Instance_tcp_tempSensor.id.toZ,
      dispatchProtocol = iDispatchProtocol.Periodic,
      state = ISZ(
        Port(
          name = "currentTemp",
          id = Arch.BuildingControlDemo_i_Instance_tcp_tempSensor.currentTemp.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.Out,
          slangType = ""),
        Port(
          name = "tempChanged",
          id = Arch.BuildingControlDemo_i_Instance_tcp_tempSensor.tempChanged.id.toZ,
          kind = PortKind.Event,
          direction = StateDirection.Out,
          slangType = "")))

  val TempControl_i_tcp_tempControl_MI : Component =
    Component(
      name = "TempControl_i_tcp_tempControl",
      id = Arch.BuildingControlDemo_i_Instance_tcp_tempControl.id.toZ,
      dispatchProtocol = iDispatchProtocol.Sporadic,
      state = ISZ(
        Port(
          name = "currentTemp",
          id = Arch.BuildingControlDemo_i_Instance_tcp_tempControl.currentTemp.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "fanAck",
          id = Arch.BuildingControlDemo_i_Instance_tcp_tempControl.fanAck.id.toZ,
          kind = PortKind.EventData,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "setPoint",
          id = Arch.BuildingControlDemo_i_Instance_tcp_tempControl.setPoint.id.toZ,
          kind = PortKind.EventData,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "fanCmd",
          id = Arch.BuildingControlDemo_i_Instance_tcp_tempControl.fanCmd.id.toZ,
          kind = PortKind.EventData,
          direction = StateDirection.Out,
          slangType = ""),
        Port(
          name = "tempChanged",
          id = Arch.BuildingControlDemo_i_Instance_tcp_tempControl.tempChanged.id.toZ,
          kind = PortKind.Event,
          direction = StateDirection.In,
          slangType = "")))

  val Fan_i_tcp_fan_MI : Component =
    Component(
      name = "Fan_i_tcp_fan",
      id = Arch.BuildingControlDemo_i_Instance_tcp_fan.id.toZ,
      dispatchProtocol = iDispatchProtocol.Sporadic,
      state = ISZ(
        Port(
          name = "fanCmd",
          id = Arch.BuildingControlDemo_i_Instance_tcp_fan.fanCmd.id.toZ,
          kind = PortKind.EventData,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "fanAck",
          id = Arch.BuildingControlDemo_i_Instance_tcp_fan.fanAck.id.toZ,
          kind = PortKind.EventData,
          direction = StateDirection.Out,
          slangType = "")))

  val modelInfo: ModelInfo =
    ModelInfo(ISZ(
     TempSensor_i_tcp_tempSensor_MI,
     TempControl_i_tcp_tempControl_MI,
     Fan_i_tcp_fan_MI))
}

@datatype class ModelInfo(val components: ISZ[Component])

@datatype class Component(val name: String,
                          val id: Z,
                          val dispatchProtocol: iDispatchProtocol.Type,
                          val state: ISZ[StateElement])

@enum object iDispatchProtocol {
  "Sporadic"
  "Periodic"
}

@enum object StateDirection {
  "In"
  "Out"
}

@sig trait StateElement {
  def name: String

  def id: Z

  def slangType: String

  def direction: StateDirection.Type
}

@enum object PortKind {
  "Data"
  "Event"
  "EventData"
}

@datatype class Port(val name: String,
                     val id: Z,
                     val kind: PortKind.Type,
                     val direction: StateDirection.Type,
                     val slangType: String) extends StateElement

@datatype class StateVariable(val name: String,
                              val id: Z,
                              val direction: StateDirection.Type,
                              val slangType: String) extends StateElement
