// #Sireum

package bc.runtimemonitor

import org.sireum._
import bc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object ObservationKind {
  "BuildingControlDemo_i_Instance_tcp_tempSensor_postInit"
  "BuildingControlDemo_i_Instance_tcp_tempSensor_preCompute"
  "BuildingControlDemo_i_Instance_tcp_tempSensor_postCompute"
  "BuildingControlDemo_i_Instance_tcp_tempControl_postInit"
  "BuildingControlDemo_i_Instance_tcp_tempControl_preCompute"
  "BuildingControlDemo_i_Instance_tcp_tempControl_postCompute"
  "BuildingControlDemo_i_Instance_tcp_fan_postInit"
  "BuildingControlDemo_i_Instance_tcp_fan_preCompute"
  "BuildingControlDemo_i_Instance_tcp_fan_postCompute"
}
