// #Sireum

package bc.BuildingControl

import org.sireum._
import art._
import bc.SystemTestSuiteSlang.runtimeMonitorStream
import bc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Fan_i_tcp_fan_SystemTestAPI {
  /** helper method to set the values of all incoming ports
    * @param api_fanCmd incoming event data port
    */
  def put_concrete_inputs(api_fanCmd: Option[BuildingControl.FanCmd.Type]): Unit = {
    put_fanCmd(api_fanCmd)
  }

  // setter for incoming event data port
  def put_fanCmd(value: Option[BuildingControl.FanCmd.Type]): Unit = {
    value match {
      case Some(v) => Art.insertInInfrastructurePort(Arch.BuildingControlDemo_i_Instance_tcp_fan.operational_api.fanCmd_Id, BuildingControl.FanCmd_Payload(v))
      case _ =>
    }
  }

  def fetchContainer(): bc.BuildingControl.Fan_i_tcp_fan_PostState_Container_PS = {
    if (runtimeMonitorStream.contains(Arch.BuildingControlDemo_i_Instance_tcp_fan.id)) {
      val (_, postContainer_) = runtimeMonitorStream.get(Arch.BuildingControlDemo_i_Instance_tcp_fan.id).get
      return postContainer_.asInstanceOf[bc.BuildingControl.Fan_i_tcp_fan_PostState_Container_PS]
    }
    else {
      assert(F, s"No post state recorded for ${Arch.BuildingControlDemo_i_Instance_tcp_fan.name}")
      halt(s"No post state recorded for ${Arch.BuildingControlDemo_i_Instance_tcp_fan.name}")
    }
  }

  def check_concrete_outputs(api_fanAck: Option[BuildingControl.FanAck.Type]): Unit = {
    var failureReasons: ISZ[ST] = ISZ()

    val actual_fanAck = get_api_fanAck()
    if (api_fanAck != actual_fanAck) {
      failureReasons = failureReasons :+ st"'fanAck' did not match expected.  Expected: $api_fanAck, Actual: $actual_fanAck"
    }

    assert(failureReasons.isEmpty, st"${(failureReasons, "\n")}".render)
  }

  def get_api_fanAck(): Option[BuildingControl.FanAck.Type] = {
    return fetchContainer().api_fanAck
  }
}