// #Sireum

package bc.BuildingControl

import org.sireum._
import bc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait Fan_i_tcp_fan_PreState_Container extends art.DataContent {
  def api_fanCmd: Option[BuildingControl.FanCmd.Type]
}

// container for incoming ports
@datatype class Fan_i_tcp_fan_PreState_Container_P (
  val api_fanCmd: Option[BuildingControl.FanCmd.Type]) extends Fan_i_tcp_fan_PreState_Container

// container for incoming ports and state variables
@datatype class Fan_i_tcp_fan_PreState_Container_PS (
  val api_fanCmd: Option[BuildingControl.FanCmd.Type]) extends Fan_i_tcp_fan_PreState_Container

@sig trait Fan_i_tcp_fan_PostState_Container extends art.DataContent {
  def api_fanAck: Option[BuildingControl.FanAck.Type]
}

// container for outgoing ports
@datatype class Fan_i_tcp_fan_PostState_Container_P (
  val api_fanAck: Option[BuildingControl.FanAck.Type]) extends Fan_i_tcp_fan_PostState_Container

// container for outgoing ports and state variables
@datatype class Fan_i_tcp_fan_PostState_Container_PS (
  val api_fanAck: Option[BuildingControl.FanAck.Type]) extends Fan_i_tcp_fan_PostState_Container
