// #Sireum

package offon.Off_On

import org.sireum._
import art._
import offon._
import offon.Off_On.{Off_p_off => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class Off_p_off_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  turnOff: Port[Base_Types.Integer],
  turnOn: Port[Base_Types.Integer]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](turnOff),

    eventOuts = ISZ[art.UPort](turnOn)
  )

  val initialization_api : Off_Initialization_Api = {
    val api = Off_Initialization_Api(
      id,
      turnOff.id,
      turnOn.id
    )
    Off_p_off_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : Off_Operational_Api = {
    val api = Off_Operational_Api(
      id,
      turnOff.id,
      turnOn.id
    )
    Off_p_off_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    Off_p_off_Bridge.EntryPoints(
      id,

      turnOff.id,
      turnOn.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object Off_p_off_Bridge {

  var c_initialization_api: Option[Off_Initialization_Api] = None()
  var c_operational_api: Option[Off_Operational_Api] = None()

  @datatype class EntryPoints(
    Off_p_off_BridgeId : Art.BridgeId,
    turnOff_Id : Art.PortId,
    turnOn_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: Off_Initialization_Api,
    operational_api: Off_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS()

    val eventInPortIds: ISZ[Art.PortId] = IS(turnOff_Id)

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS(turnOn_Id)

    def initialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: Off_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: Off_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def activate(): Unit = {
      // implement the following method in 'component':  def activate(api: Off_Operational_Api): Unit = {}
      component.activate(operational_api)
    }

    def deactivate(): Unit = {
      // implement the following method in 'component':  def deactivate(api: Off_Operational_Api): Unit = {}
      component.deactivate(operational_api)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: Off_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    def recover(): Unit = {
      // implement the following method in 'component':  def recover(api: Off_Operational_Api): Unit = {}
      component.recover(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: Off_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: Off_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}